### ISSUE TITLE
make fails

### ISSUE THREAD

**Issue by ericandrewlewis** [ProseMirror/website#19]
The build is looking for CHANGELOG.md in the `prosemirror` package, which only exists in vesrion 0.2.0. Perhaps we should update the `package.json` of this repo to reflect this?

```
> $ make                                                                                                                                     
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^
Error: ENOENT: no such file or directory, open '/Users/eric/Code/github/ProseMirror/website/src/build/../../markdown/../node_modules/prosemirror/CHANGELOG.md'
    at Error (native)
    at Object.fs.openSync (fs.js:584:18)
    at Object.fs.readFileSync (fs.js:431:33)
    at mold.defs.markdownFile (/Users/eric/Code/github/ProseMirror/website/src/build/templates.js:17:34)
    at Mold.dispatch (/Users/eric/Code/github/ProseMirror/website/node_modules/mold-template/mold.js:30:25)
    at eval (eval at evaluate (/Users/eric/Code/github/ProseMirror/website/node_modules/mold-template/mold.js:180:10), <anonymous>:8:12)
    at /Users/eric/Code/github/ProseMirror/website/src/build/build.js:36:35
    at Array.forEach (native)
    at Object.<anonymous> (/Users/eric/Code/github/ProseMirror/website/src/build/build.js:27:7)
    at Module._compile (module.js:398:26)
make: *** [public/changelog.html] Error 1
```

**Comment by marijnh** [comment]
Yeah, that would make sense.

I think in general, I'm not really willing to commit to the website being buildable by anyone at any point in time. I can see how that is desirable, but given all the churn the project is experiencing, it would take a bunch of energy to keep all the details lined up all the time, and I'd rather spend that energy on other things.
