### ISSUE TITLE
TypeError: newInstance is not a function running demo locally with empty "demo-instances.json"

### ISSUE THREAD

**Issue by jtblin** [ProseMirror/website#32]
I am getting the following error when following the readme instructions to run the demo locally. I think the issue is due to cyclic import of "./instance" between "instance.js" and "defaultinstances.js".

```
$ npm start

> prosemirror-website@0.0.1 start /Users/jtblin/src/product-fabric/ProseMirror/website
> node src/demo/collab/server/start.js

/Users/jtblin/src/product-fabric/ProseMirror/website/src/demo/collab/server/defaultinstances.js:9
newInstance("Example", $node("doc", null, [
^

TypeError: newInstance is not a function
    at populateDefaultInstances (/Users/jtblin/src/product-fabric/ProseMirror/website/src/demo/collab/server/defaultinstances.js:9:1)
    at Object.<anonymous> (/Users/jtblin/src/product-fabric/ProseMirror/website/src/demo/collab/server/instance.js:132:3)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/jtblin/src/product-fabric/ProseMirror/website/src/demo/collab/server/server.js:6:37)
```

**Comment by marijnh** [comment]
Thanks for reporting that, and thanks for the pull request! I've pushed a somewhat simpler patch  d4308ba to resolve it
