### ISSUE TITLE
dinos demo broken

### ISSUE THREAD

**Issue by dlants** [ProseMirror/website#53]
```
2017-03-16 14:46:08.923 example.js:53 Uncaught TypeError: MenuItem is not a constructor
    at http://prosemirror.net/examples/dino/example.js:53:62
    at Array.map (native)
    at Object.1.prosemirror-example-setup (http://prosemirror.net/examples/dino/example.js:53:33)
    at s (http://prosemirror.net/examples/dino/example.js:1:254)
    at e (http://prosemirror.net/examples/dino/example.js:1:425)
    at http://prosemirror.net/examples/dino/example.js:1:443```

**Comment by marijnh** [comment]
Fixed by 40f9dd768fba32
